# Generated by Django 4.0 on 2022-01-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.AddField(
            model_name='event',
            name='processes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
