# Generated by Django 4.0 on 2022-01-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_event_event_type_event_processes_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loggerkey',
            table='logger_key',
        ),
    ]
